CREATE TABLE IF NOT EXISTS "ec01-users" (
	"id_user" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tx_name" VARCHAR(255) NOT NULL,
	"tx_email" VARCHAR(255) NOT NULL,
	"tx_phone_number" VARCHAR(15) NOT NULL,
	PRIMARY KEY("id_user")
);




CREATE TABLE IF NOT EXISTS "ec03-address" (
	"id_address" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tx_street " VARCHAR(255) NOT NULL,
	"tx_external_numer " VARCHAR(255) NOT NULL,
	"tx_cp" VARCHAR(5) NOT NULL,
	"tx_internal_number" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_address")
);




CREATE TABLE IF NOT EXISTS "ec05-payment-methods" (
	"id_payment" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"carnumber" VARCHAR(255) NOT NULL,
	"titularname" VARCHAR(255) NOT NULL,
	"firstname" VARCHAR(255) NOT NULL,
	"secondname" VARCHAR(255) NOT NULL,
	"lastname" VARCHAR(255) NOT NULL,
	"secondlastname" VARCHAR(255) NOT NULL,
	"expirationdate" DATE NOT NULL,
	"cvc" VARCHAR(3) NOT NULL,
	PRIMARY KEY("id_payment")
);




CREATE TABLE IF NOT EXISTS "ec04-user-payment" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fk_id_user" INTEGER NOT NULL,
	"fk_id_payment" INTEGER NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ec02-user-address" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fk_id_user" INTEGER NOT NULL,
	"fk_id_address" INTEGER NOT NULL,
	PRIMARY KEY("id")
);



ALTER TABLE "ec04-user-payment"
ADD FOREIGN KEY("fk_id_user") REFERENCES "ec01-users"("id_user")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ec04-user-payment"
ADD FOREIGN KEY("fk_id_payment") REFERENCES "ec05-payment-methods"("id_payment")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ec02-user-address"
ADD FOREIGN KEY("fk_id_user") REFERENCES "ec01-users"("id_user")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ec02-user-address"
ADD FOREIGN KEY("fk_id_address") REFERENCES "ec03-address"("id_address")
ON UPDATE NO ACTION ON DELETE NO ACTION;