CREATE TABLE IF NOT EXISTS "ec01_users" (
	"id_user" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tx_name" VARCHAR(255) NOT NULL,
	"tx_email" VARCHAR(255) NOT NULL,
	"tx_phone_number" VARCHAR(15) NOT NULL,
    "tx_password" VARCHAR(60) NOT NULL,
	PRIMARY KEY("id_user")
);




CREATE TABLE IF NOT EXISTS "ec03_address" (
	"id_address" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tx_street " VARCHAR(255) NOT NULL,
	"tx_external_number " VARCHAR(255) NOT NULL,
	"tx_cp" VARCHAR(5) NOT NULL,
	"tx_internal_number" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_address")
);




CREATE TABLE IF NOT EXISTS "ec05_payment_methods" (
	"id_payment" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tx_card_number" VARCHAR(255) NOT NULL,
	"tx_titular_name" VARCHAR(255) NOT NULL,
	"tx_first_name" VARCHAR(255) NOT NULL,
	"tx_second_name" VARCHAR(255) NOT NULL,
	"tx_last_name" VARCHAR(255) NOT NULL,
	"tx_second_lastname" VARCHAR(255) NOT NULL,
	"dt_expiration_date" DATE NOT NULL,
	"tx_cvc" VARCHAR(3) NOT NULL,
	PRIMARY KEY("id_payment")
);




CREATE TABLE IF NOT EXISTS "ec04_user_payment" (
	"id_user_payment" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fk_id_user" INTEGER NOT NULL,
	"fk_id_payment" INTEGER NOT NULL,
	PRIMARY KEY("id_user_payment")
);




CREATE TABLE IF NOT EXISTS "ec02_user_address" (
	"id_user_address" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fk_id_user" INTEGER NOT NULL,
	"fk_id_address" INTEGER NOT NULL,
	PRIMARY KEY("id_user_address")
);
CREATE TABLE IF NOT EXISTS "ec06_tokens"(
    "id_token" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "tx_token" TEXT NOT NULL,
	"tx_token_type" VARCHAR(50) NOT NULL,
    "st_revoked" BOOLEAN NOT NULL,
    "st_expired" BOOLEAN NOT NULL,
    "fk_id_user" INTEGER NOT NULL,
    PRIMARY KEY ("id_token")
);


ALTER TABLE "ec04_user_payment"
ADD FOREIGN KEY("fk_id_user") REFERENCES "ec01_users"("id_user")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ec04_user_payment"
ADD FOREIGN KEY("fk_id_payment") REFERENCES "ec05_payment_methods"("id_payment")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ec02_user_address"
ADD FOREIGN KEY("fk_id_user") REFERENCES "ec01_users"("id_user")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ec02_user_address"
ADD FOREIGN KEY("fk_id_address") REFERENCES "ec03_address"("id_address")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ec06_tokens"
ADD FOREIGN KEY("fk_id_user") REFERENCES "ec01_users"("id_user")
ON UPDATE NO ACTION ON DELETE NO ACTION;